var inputName =document.querySelector("#inputName")
var inputEmail =document.querySelector("#Email")
var inputJob =document.querySelector("#Job")
var tbody =document.querySelector("#tbody")
var btn =document.querySelector("#btn")
// console.log(inputName)
// console.log(email)
// console.log(job)
// console.log(tbody)